'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import Logo from '@/components/Logo';

const FAQS = [
  {
    q: "I can’t find my item category or have a special request. How do I add it?",
    a: "If you are unsure which category fits your specific item, want to ship a unique product that isn't listed on our platform, or have general questions about what can be shipped, get in touch with us directly! Our support team is always available to help you figure out the best way to categorize and route your special items."
  },
  {
    q: "What happens if the actual weight of my items is different from the estimate?",
    a: "Our system provides a smart estimate used for your initial booking. Once your items arrive at our warehouse, we verify their actual physical weight. If they weigh more than expected or were categorized differently, there are no penalty fees. We will simply send you an update detailing the exact difference and provide a 12-hour review window before any outstanding balance needs to be cleared for final dispatch."
  },
  {
    q: "How does the Hold & Combine feature work, and what are \"Extras\"?",
    a: "Instead of shipping box by box, you can choose to hold your items at our warehouse and combine them with up to 3 additional incoming packages to build one cost-effective shipment. As you build your box, you can also include \"Extras\"—unlimited lightweight additions (like accessories and socks) that ship without impacting your overall weight class."
  },
  {
    q: "What if I realize I bought the wrong item and need to return it to the original store?",
    a: "If you need to return a retail item, you must initiate the return before your final parcel is consolidated and packed for its final destination. Simply provide us with the digital return label generated by the original online store. A small processing fee applies for our team to print the label, attach it, and hand it to the courier. If a courier is coming to our facility to pick it up, we require 24 hours' advance notice."
  },
  {
    q: "Can I cancel my shipment or change my delivery address after my box is packed?",
    a: "No. Once your items are received and our team has automatically consolidated and packed your final parcel for transit, the shipment is locked in. It cannot be canceled, modified, or halted, and shipping fees will not be refunded. Additionally, you must ensure your final delivery address is correct before your items arrive at our warehouse. We cannot reroute packages or issue refunds for deliveries sent to an incorrect address originally provided by you."
  },
  {
    q: "When will I get my tracking number?",
    a: "Your unique tracking ID is generated and shared once we have received your items, combined your orders (if requested), verified the final weight, and your parcel is fully packed and ready to ship out to its final destination. You can easily find this tracking number in your account dashboard and monitor real-time updates from the moment it leaves our warehouse."
  },
  {
    q: "Are there any items I am not allowed to ship?",
    a: "Yes. All shipments must comply with standard legal and carrier shipping policies. We cannot process or forward illegal, hazardous, or prohibited goods. Additionally, we strongly advise against shipping inherently fragile items or products prone to leaking (such as liquids, oils, or perishables). Layo does not accept liability for damages caused to or by these items during transit."
  },
  {
    q: "Can I estimate my shipping costs before I actually buy anything?",
    a: "Absolutely. We offer a built-in Shipping Calculator so you can plan your smart haul. Simply select the categories of the items you plan to purchase to get a clear, upfront estimate. There is no commitment—you can check your estimated costs today and route your packages to our warehouse whenever you are ready."
  },
  {
    q: "Can I use Layo for personal packages sent by family or friends?",
    a: "Yes! Layo is built for total flexibility. Whether it is a bulk order from an online store, an offline purchase at a local retailer, or a personal care package from home, simply provide the sender with the Layo warehouse address listed in your account, and we will seamlessly receive and manage your items."
  }
];

export default function FAQPage() {
  const router = useRouter();
  const [openIdx, setOpenIdx] = useState<number | null>(0);
  const [search, setSearch] = useState('');

  const filteredFaqs = FAQS.filter(
    f => f.q.toLowerCase().includes(search.toLowerCase()) || f.a.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="bg-[#f5f2eb] text-[#2b2927] min-h-screen flex flex-col">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-[#f5f2eb]/90 backdrop-blur-md border-b border-black/5 px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <button
            onClick={() => router.back()}
            className="w-9 h-9 rounded-full border border-black/10 flex items-center justify-center text-[#5c5752] hover:text-[#2b2927] hover:border-black/30 transition-colors cursor-pointer"
          >
            <span className="material-symbols-outlined text-lg">arrow_back</span>
          </button>
          <Link href="/">
            <Logo showTagline={false} darkText={true} />
          </Link>
        </div>
        <div className="flex items-center gap-4">
          <Link
            href="/login"
            className="px-4 py-2 bg-primary text-[#241a00] font-bold text-xs uppercase tracking-wider rounded-full hover:brightness-105 transition-all shadow-sm"
          >
            Sign Up / Log In
          </Link>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-grow max-w-4xl mx-auto w-full px-6 py-12 space-y-8">
        <div className="bg-white border border-[#e5e0d8] rounded-3xl p-8 md:p-12 shadow-sm space-y-8">
          <div className="text-center space-y-3 max-w-xl mx-auto">
            <span className="text-xs font-bold uppercase tracking-[0.25em] text-[#5c5752]">Help Center</span>
            <h1 className="text-3xl md:text-5xl font-bold text-[#1c1917] font-serif-luxury">
              Frequently Asked Questions
            </h1>
            <p className="text-sm text-[#5c5752] leading-relaxed">
              Find instant answers to common questions about parcel holding, combining orders, shipping calculators, and delivery rules.
            </p>

            {/* Search Input */}
            <div className="relative pt-2">
              <span className="material-symbols-outlined absolute left-4 top-5 text-[#888]">search</span>
              <input
                type="text"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder="Search FAQs..."
                className="w-full pl-12 pr-4 py-3.5 bg-[#faf8f5] border border-[#e6e1da] rounded-2xl text-sm text-[#2b2927] placeholder:text-[#a09a90] focus:outline-none focus:border-primary"
              />
            </div>
          </div>

          {/* Accordion FAQ List */}
          <div className="border-t border-[#e5e0d8] pt-8 space-y-4">
            {filteredFaqs.map((faq, idx) => {
              const isOpen = openIdx === idx;
              return (
                <div
                  key={idx}
                  className="border border-[#e5e0d8] rounded-2xl overflow-hidden bg-[#faf8f5] transition-all"
                >
                  <button
                    onClick={() => setOpenIdx(isOpen ? null : idx)}
                    className="w-full px-6 py-5 flex items-center justify-between text-left font-bold text-sm text-[#1c1917] hover:text-black cursor-pointer gap-4"
                  >
                    <span>{faq.q}</span>
                    <span className="material-symbols-outlined text-primary text-xl flex-shrink-0">
                      {isOpen ? 'remove_circle' : 'add_circle'}
                    </span>
                  </button>

                  {isOpen && (
                    <div className="px-6 pb-5 pt-1 text-xs text-[#5c5752] leading-relaxed border-t border-black/5 bg-white">
                      {faq.a}
                    </div>
                  )}
                </div>
              );
            })}

            {filteredFaqs.length === 0 && (
              <p className="text-center py-8 text-xs text-[#5c5752]">
                No matching FAQs found. Try another search term.
              </p>
            )}
          </div>

          <div className="border-t border-[#e5e0d8] pt-6 text-center space-y-3">
            <p className="text-xs text-[#5c5752]">Got more questions? Get in touch with us directly!</p>
            <Link
              href="/#contact"
              className="inline-block px-6 py-3 bg-primary text-[#241a00] font-bold text-xs uppercase tracking-wider rounded-xl hover:brightness-105 transition-all shadow-sm"
            >
              Contact Support
            </Link>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-black/5 bg-[#eae7de] py-6 px-6 text-center text-xs text-[#5c5752]">
        <p>© 2026 Layo Technologies Inc. All rights reserved.</p>
      </footer>
    </div>
  );
}
