'use client';

import { useState, useRef, useEffect } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import Logo from '@/components/Logo';
import EstimatorModal from '@/components/EstimatorModal';

// Step item structure for timeline
interface TimelineStep {
  title: string;
  desc: string;
}

const NEW_USER_STEPS: TimelineStep[] = [
  { title: 'Sign Up.', desc: 'Create your Layo account.' },
  { title: 'Shop & Send.', desc: 'Shop from anywhere in India and send your orders to your Layo address.' },
  { title: 'Enter Order Details', desc: 'Input the store name and your specific order or reference number.' },
  { title: 'Build Your Shipment.', desc: 'Categorise items, add destinations, and shipping preferences.' },
  { title: 'Ship or Hold', desc: 'Ship immediately, or hold to combine with up to 3 incoming packages.' },
  { title: 'Review & Pay.', desc: 'Confirm details and complete payment.' },
  { title: 'Track & Receive.', desc: 'Follow your shipment until it arrives.' },
];

const EXISTING_USER_STEPS: TimelineStep[] = [
  { title: 'Log In.', desc: 'Log in to your existing Layo account.' },
  { title: 'Shop & Send.', desc: 'Shop from anywhere in India and send your orders to your Layo address.' },
  { title: 'Enter Order Details', desc: 'Input the store name and your specific order or reference number.' },
  { title: 'Build Your Shipment.', desc: 'Categorise items, add destinations, and shipping preferences.' },
  { title: 'Ship or Hold', desc: 'Ship immediately, or hold to combine with up to 3 incoming packages.' },
  { title: 'Review & Pay.', desc: 'Confirm details and complete payment.' },
  { title: 'Track & Receive.', desc: 'Follow your shipment until it arrives.' },
];

const PERSONAL_USER_STEPS: TimelineStep[] = [
  { title: 'Select Personal Shipping', desc: 'Choose Personal/Home Package to start routing your everyday belongings or gifts.' },
  { title: 'Enter Sender Details', desc: "Enter the sender's name and the city the package is coming from." },
  { title: 'Route Your Package', desc: 'Assign a warehouse and share its address with your sender (or use it to mail the package yourself), then enter your final delivery address.' },
  { title: 'Ship or Hold', desc: 'Ship immediately, or hold to combine with up to 3 incoming packages.' },
  { title: 'Review & Pay.', desc: 'Confirm details and complete payment.' },
  { title: 'Track & Receive.', desc: 'Follow your shipment until it arrives.' },
];

const FAQS_LIST = [
  {
    q: "1. I can’t find my item category or have a special request. How do I add it?",
    a: "If you are unsure which category fits your specific item, want to ship a unique product that isn't listed on our platform, or have general questions about what can be shipped, get in touch with us directly! Our support team is always available to help you figure out the best way to categorize and route your special items."
  },
  {
    q: "2. What happens if the actual weight of my items is different from the estimate?",
    a: "Our system provides a smart estimate used for your initial booking. Once your items arrive at our warehouse, we verify their actual physical weight. If they weigh more than expected or were categorized differently, there are no penalty fees. We will simply send you an update detailing the exact difference and provide a 12-hour review window before any outstanding balance needs to be cleared for final dispatch."
  },
  {
    q: "3. How does the Hold & Combine feature work, and what are \"Extras\"?",
    a: "Instead of shipping box by box, you can choose to hold your items at our warehouse and combine them with up to 3 additional incoming packages to build one cost-effective shipment. As you build your box, you can also include \"Extras\"—unlimited lightweight additions (like accessories and socks) that ship without impacting your overall weight class."
  },
  {
    q: "4. What if I realize I bought the wrong item and need to return it to the original store?",
    a: "If you need to return a retail item, you must initiate the return before your final parcel is consolidated and packed for its final destination. Simply provide us with the digital return label generated by the original online store. A small processing fee applies for our team to print the label, attach it, and hand it to the courier. If a courier is coming to our facility to pick it up, we require 24 hours' advance notice."
  },
  {
    q: "5. Can I cancel my shipment or change my delivery address after my box is packed?",
    a: "No. Once your items are received and our team has automatically consolidated and packed your final parcel for transit, the shipment is locked in. It cannot be canceled, modified, or halted, and shipping fees will not be refunded. Additionally, you must ensure your final delivery address is correct before your items arrive at our warehouse. We cannot reroute packages or issue refunds for deliveries sent to an incorrect address originally provided by you."
  },
  {
    q: "6. When will I get my tracking number?",
    a: "Your unique tracking ID is generated and shared once we have received your items, combined your orders (if requested), verified the final weight, and your parcel is fully packed and ready to ship out to its final destination. You can easily find this tracking number in your account dashboard and monitor real-time updates from the moment it leaves our warehouse."
  },
  {
    q: "7. Are there any items I am not allowed to ship?",
    a: "Yes. All shipments must comply with standard legal and carrier shipping policies. We cannot process or forward illegal, hazardous, or prohibited goods. Additionally, we strongly advise against shipping inherently fragile items or products prone to leaking (such as liquids, oils, or perishables). Layo does not accept liability for damages caused to or by these items during transit."
  },
  {
    q: "8. Can I estimate my shipping costs before I actually buy anything?",
    a: "Absolutely. We offer a built-in Shipping Calculator so you can plan your smart haul. Simply select the categories of the items you plan to purchase to get a clear, upfront estimate. There is no commitment—you can check your estimated costs today and route your packages to our warehouse whenever you are ready."
  },
  {
    q: "9. Can I use Layo for personal packages sent by family or friends?",
    a: "Yes! Layo is built for total flexibility. Whether it is a bulk order from an online store, an offline purchase at a local retailer, or a personal care package from home, simply provide the sender with the Layo warehouse address listed in your account, and we will seamlessly receive and manage your items."
  }
];

export default function KnowMorePage() {
  // Tabbed timeline state
  const [activeTab, setActiveTab] = useState<'new' | 'existing' | 'personal'>('new');
  // FAQ accordion state
  const [openFaqIdx, setOpenFaqIdx] = useState<number | null>(0);
  // Estimator modal
  const [modalOpen, setModalOpen] = useState(false);
  // Contact form
  const [contactForm, setContactForm] = useState({ name: '', contact: '', message: '' });
  const [contactSubmitted, setContactSubmitted] = useState(false);

  // Refs
  const aboutRef = useRef<HTMLDivElement>(null);
  const faqRef = useRef<HTMLDivElement>(null);
  const contactRef = useRef<HTMLDivElement>(null);

  const activeSteps = activeTab === 'new'
    ? NEW_USER_STEPS
    : activeTab === 'existing'
      ? EXISTING_USER_STEPS
      : PERSONAL_USER_STEPS;

  useEffect(() => {
    if (typeof window !== 'undefined' && window.location.hash) {
      const hash = window.location.hash;
      if (hash === '#contact' || hash === '#contact-section') {
        setTimeout(() => {
          contactRef.current?.scrollIntoView({ behavior: 'smooth' });
        }, 150);
      }
    }
  }, []);

  const handleContactSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!contactForm.name || !contactForm.contact) return;
    setContactSubmitted(true);
    setTimeout(() => {
      setContactForm({ name: '', contact: '', message: '' });
    }, 3000);
  };

  return (
    <div className="bg-[#FAF8EE] text-[#0E1F38] min-h-screen flex flex-col overflow-x-hidden relative font-sans">

      {/* ── HEADER ── */}
      <header className="sticky top-0 w-full h-[10vh] z-[100] flex items-center justify-between px-6 md:px-16 bg-[#FAF8EE]/90 backdrop-blur-md border-b border-black/5 shadow-sm">
        <div className="flex items-center gap-4">
          <Link href="/" className="text-[#0E1F38] hover:text-[#FF5A65] transition-colors">
            <span className="material-symbols-outlined text-2xl">arrow_back</span>
          </Link>
          <Logo showTagline={false} darkText={true} />
        </div>
        <nav className="hidden md:flex items-center gap-8 font-semibold text-sm">
          <Link href="/know-more" className="text-[#0E1F38] hover:text-[#FF5A65] transition-colors">How it Works</Link>
          <Link href="/shipping-policy" className="text-[#0E1F38] hover:text-[#FF5A65] transition-colors">Shipping Policy</Link>
          <Link href="/login" className="text-[#0E1F38] hover:text-[#FF5A65] transition-colors">Sign Up/Log In</Link>
        </nav>
      </header>

      {/* ───────────────────────────────────────
          SECTION 1: HERO & INTERACTIVE TIMELINE
      ─────────────────────────────────────── */}
      <section className="py-20 px-6 md:px-16">
        <div className="max-w-5xl w-full mx-auto space-y-10">

          {/* Title */}
          <div className="text-left space-y-2">
            <h1 className="text-4xl md:text-6xl font-black tracking-tight text-[#0E1F38]">
              Indian Shipping<br />
              Made <span className="text-[#FF5A65] italic font-serif-luxury font-medium">Easy.</span>
            </h1>
          </div>

          {/* 3-Tab Selector */}
          <div className="flex flex-wrap gap-2 border-b border-black/10 pb-4">
            <button
              onClick={() => setActiveTab('new')}
              className={`px-5 py-2.5 rounded-full text-xs font-bold transition-all cursor-pointer ${
                activeTab === 'new'
                  ? 'bg-[#d8e8c5] text-[#2b3a1a] shadow-sm ring-1 ring-[#b8d49a]'
                  : 'bg-white/60 text-[#0E1F38]/60 hover:bg-white'
              }`}
            >
              New users
            </button>
            <button
              onClick={() => setActiveTab('existing')}
              className={`px-5 py-2.5 rounded-full text-xs font-bold transition-all cursor-pointer ${
                activeTab === 'existing'
                  ? 'bg-[#f7c5b8] text-[#4a1c12] shadow-sm ring-1 ring-[#e8a392]'
                  : 'bg-white/60 text-[#0E1F38]/60 hover:bg-white'
              }`}
            >
              Existing Users
            </button>
            <button
              onClick={() => setActiveTab('personal')}
              className={`px-5 py-2.5 rounded-full text-xs font-bold transition-all cursor-pointer ${
                activeTab === 'personal'
                  ? 'bg-[#cbe6f7] text-[#14344d] shadow-sm ring-1 ring-[#9fcde8]'
                  : 'bg-white/60 text-[#0E1F38]/60 hover:bg-white'
              }`}
            >
              Home & Personal
            </button>
          </div>

          {/* Personal belongings banner subtitle if active */}
          {activeTab === 'personal' && (
            <div className="bg-[#dcf0fa] border border-[#bce0f5] rounded-xl px-4 py-2.5 text-xs font-bold text-[#14344d]">
              For your everyday belongings & gifts.
            </div>
          )}

          {/* Interactive Steps Layout & Cardboard Box Illustration */}
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-start">
            {/* Timeline Steps (7 cols) */}
            <div className="lg:col-span-7 relative pl-8 space-y-6">
              {/* Vertical connecting line */}
              <div className="absolute left-[11px] top-3 bottom-3 w-0.5 bg-[#0E1F38]" />

              {activeSteps.map((step, idx) => (
                <div key={idx} className="relative flex items-start gap-4 group">
                  {/* Timeline dot */}
                  <div className="absolute -left-[33px] top-1.5 w-3 h-3 rounded-full bg-[#0E1F38] border-2 border-[#FAF8EE] shadow-sm" />
                  <div>
                    <h3 className="text-base font-bold text-[#0E1F38] leading-snug">{step.title}</h3>
                    <p className="text-xs text-[#0E1F38]/70 leading-relaxed mt-0.5 font-light">{step.desc}</p>
                  </div>
                </div>
              ))}
            </div>

            {/* Box Illustration (5 cols) */}
            <div className="lg:col-span-5 flex flex-col items-center justify-center relative">
              <div className="w-full max-w-[440px] relative">
                <Image
                  src="/how-layo-works-box.png"
                  alt="How Layo Works - Combine Orders, Safe In Your Locker, Hold Orders Up To 30 Days"
                  width={1024}
                  height={621}
                  className="w-full h-auto object-contain drop-shadow-md rounded-3xl transition-transform hover:scale-[1.02] duration-300"
                  priority
                />
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ───────────────────────────────────────
          SECTION 2: HOW LAYO WORKS (4-Step Grid)
      ─────────────────────────────────────── */}
      <section className="py-20 px-6 md:px-16 bg-[#ECEAE0] border-y border-black/5">
        <div className="max-w-5xl w-full mx-auto space-y-12">
          <div className="text-center space-y-3 max-w-2xl mx-auto">
            <h2 className="text-3xl md:text-5xl font-black tracking-tight text-[#0E1F38]">
              How <span className="text-[#FF5A65] italic font-serif-luxury font-medium">Layo</span> Works
            </h2>
            <p className="text-sm md:text-base text-[#0E1F38]/70 font-light leading-relaxed">
              Every order you place in India lands safely in your own Layo warehouse locker — ready to combine, pack, and send whenever you are.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            <div className="bg-white border border-black/5 rounded-3xl p-6 flex flex-col space-y-4 shadow-sm hover:shadow-md transition-shadow">
              <div className="flex justify-between items-center">
                <span className="text-2xl font-black text-[#FF5A65]">01</span>
                <span className="text-2xl">📍</span>
              </div>
              <h3 className="text-lg font-bold text-[#0E1F38]">Route Your Packages</h3>
              <p className="text-xs text-[#0E1F38]/75 leading-relaxed font-light">Whether you are shopping online or offline, or receiving a personal package, simply use your provided warehouse address as your delivery destination.</p>
            </div>
            <div className="bg-white border border-black/5 rounded-3xl p-6 flex flex-col space-y-4 shadow-sm hover:shadow-md transition-shadow">
              <div className="flex justify-between items-center">
                <span className="text-2xl font-black text-[#FF5A65]">02</span>
                <span className="text-2xl">🏷️</span>
              </div>
              <h3 className="text-lg font-bold text-[#0E1F38]">Categorize & Customize</h3>
              <p className="text-xs text-[#0E1F38]/75 leading-relaxed font-light">Ditch the guesswork by simply categorizing your items for a smart, data-driven weight estimate. Don&apos;t forget your lightweight &quot;Extras&quot;!</p>
            </div>
            <div className="bg-white border border-black/5 rounded-3xl p-6 flex flex-col space-y-4 shadow-sm hover:shadow-md transition-shadow">
              <div className="flex justify-between items-center">
                <span className="text-2xl font-black text-[#FF5A65]">03</span>
                <span className="text-2xl">🔄</span>
              </div>
              <h3 className="text-lg font-bold text-[#0E1F38]">Ship, Hold & Combine</h3>
              <p className="text-xs text-[#0E1F38]/75 leading-relaxed font-light">Ship immediately, or optionally choose to hold your items to combine them with up to 3 additional incoming packages.</p>
            </div>
            <div className="bg-white border border-black/5 rounded-3xl p-6 flex flex-col space-y-4 shadow-sm hover:shadow-md transition-shadow">
              <div className="flex justify-between items-center">
                <span className="text-2xl font-black text-[#FF5A65]">04</span>
                <span className="text-2xl">🚚</span>
              </div>
              <h3 className="text-lg font-bold text-[#0E1F38]">Ship & Track</h3>
              <p className="text-xs text-[#0E1F38]/75 leading-relaxed font-light">Review your finalized, cost-effective shipment, complete your payment, and track your smart haul right to your doorstep.</p>
            </div>
          </div>

          <div className="text-center pt-4">
            <button
              onClick={() => setModalOpen(true)}
              className="px-8 py-3.5 bg-[#FF5A65] text-white font-bold text-xs uppercase tracking-wider rounded-xl hover:bg-[#E24550] transition-all shadow-sm cursor-pointer"
            >
              Calculate Your Shipping
            </button>
          </div>
        </div>
      </section>

      {/* ───────────────────────────────────────
          SECTION 3: ABOUT LAYO
      ─────────────────────────────────────── */}
      <section ref={aboutRef} className="py-24 px-6 md:px-16 bg-[#FAF8EE]">
        <div className="max-w-5xl w-full mx-auto">
          <div className="bg-[#0E1F38] text-white rounded-3xl p-8 md:p-14 space-y-8 shadow-xl">
            <h2 className="text-3xl md:text-5xl font-black text-white tracking-tight">About Layo</h2>

            <div className="space-y-4 text-sm md:text-base text-gray-200 font-light leading-relaxed border-b border-white/15 pb-8">
              <p className="font-medium text-white">
                Shipping shouldn&apos;t be a rigid, expensive hurdle. It should adapt to how you actually shop and live.
              </p>
              <p>
                At Layo, we&apos;ve built a smart logistics platform designed to give you total control over your shipments. Whether you are routing everyday retail essentials, building a seasonal haul, or sending personal packages from home, we transform complex international shipping into a simple, stress-free experience.
              </p>
              <p>
                We believe in fair shipping. To keep your deliveries affordable and minimize volumetric weight, we employ strategic packing techniques, which includes vacuum-sealing bulky apparel whenever necessary to save space.
              </p>
              <p>
                From giving you the power to hold and combine multiple packages to introducing weight-free &quot;Extras,&quot; every feature we build is designed to optimize your shipping journey and maximize your value.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ───────────────────────────────────────
          SECTION 4: FREQUENTLY ASKED QUESTIONS
      ─────────────────────────────────────── */}
      <section ref={faqRef} className="py-20 px-6 md:px-16 bg-[#ECEAE0] border-t border-black/5">
        <div className="max-w-4xl w-full mx-auto space-y-10">
          <div className="text-center space-y-3">
            <h2 className="text-3xl md:text-5xl font-black text-[#0E1F38] tracking-tight">
              Frequently Asked Questions
            </h2>
            <p className="text-sm text-[#0E1F38]/60">
              Everything you need to know about shipping, holding, and estimates.
            </p>
          </div>

          <div className="space-y-3">
            {FAQS_LIST.map((faq, idx) => {
              const isOpen = openFaqIdx === idx;
              return (
                <div
                  key={idx}
                  className="bg-white border border-black/5 rounded-2xl overflow-hidden transition-all shadow-sm"
                >
                  <button
                    onClick={() => setOpenFaqIdx(isOpen ? null : idx)}
                    className="w-full px-6 py-4 flex items-center justify-between text-left font-bold text-sm text-[#0E1F38] hover:text-[#FF5A65] cursor-pointer gap-4"
                  >
                    <span>{faq.q}</span>
                    <span className="w-7 h-7 rounded-full bg-[#FAF8EE] text-[#FF5A65] flex items-center justify-center font-bold text-base flex-shrink-0">
                      {isOpen ? '-' : '+'}
                    </span>
                  </button>
                  {isOpen && (
                    <div className="px-6 pb-5 pt-1 text-xs text-[#0E1F38]/70 leading-relaxed border-t border-black/5 bg-[#fdfbf5]">
                      {faq.a}
                    </div>
                  )}
                </div>
              );
            })}
          </div>

          <div className="text-center pt-6 space-y-4">
            <p className="text-sm font-bold text-[#0E1F38]">
              Got more questions? Get in touch with us directly!
            </p>
          </div>
        </div>
      </section>

      {/* ───────────────────────────────────────
          SECTION 5: GET IN TOUCH WITH US HERE
      ─────────────────────────────────────── */}
      <section ref={contactRef} id="contact" className="py-24 px-6 md:px-16 bg-[#E7F7D3] border-t border-black/5 scroll-mt-16">
        <div className="max-w-4xl w-full mx-auto space-y-10">
          <div className="text-center space-y-2">
            <h2 className="text-3xl md:text-5xl font-black text-[#0E1F38] tracking-tight">
              Get In Touch With Us Here
            </h2>
          </div>

          <div className="bg-white border border-[#D5E9C0] rounded-3xl p-8 md:p-12 shadow-md space-y-6">
            {contactSubmitted ? (
              <div className="p-6 bg-green-50 border border-green-200 text-green-800 rounded-2xl text-center space-y-2">
                <span className="material-symbols-outlined text-3xl text-green-600">check_circle</span>
                <h3 className="font-bold text-base">Thank you for reaching out!</h3>
                <p className="text-xs text-green-700">Our support team will get back to you within 24 hours.</p>
              </div>
            ) : (
              <form onSubmit={handleContactSubmit} className="space-y-4">
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <input
                    type="text"
                    value={contactForm.name}
                    onChange={(e) => setContactForm({ ...contactForm, name: e.target.value })}
                    placeholder="Name"
                    className="w-full px-4 py-3.5 bg-[#fdfbf5] border border-black/5 rounded-xl text-sm text-[#0E1F38] placeholder:text-black/40 focus:outline-none focus:border-[#FF5A65]"
                    required
                  />
                  <input
                    type="text"
                    value={contactForm.contact}
                    onChange={(e) => setContactForm({ ...contactForm, contact: e.target.value })}
                    placeholder="Phone/Email"
                    className="w-full px-4 py-3.5 bg-[#fdfbf5] border border-black/5 rounded-xl text-sm text-[#0E1F38] placeholder:text-black/40 focus:outline-none focus:border-[#FF5A65]"
                    required
                  />
                </div>
                <textarea
                  rows={4}
                  value={contactForm.message}
                  onChange={(e) => setContactForm({ ...contactForm, message: e.target.value })}
                  placeholder="Message"
                  className="w-full px-4 py-3.5 bg-[#fdfbf5] border border-black/5 rounded-xl text-sm text-[#0E1F38] placeholder:text-black/40 focus:outline-none focus:border-[#FF5A65]"
                />
                <button
                  type="submit"
                  className="w-full py-4 bg-[#0E1F38] hover:bg-[#060D18] text-white font-bold text-xs uppercase tracking-widest rounded-xl transition-all shadow-md cursor-pointer"
                >
                  Submit
                </button>
              </form>
            )}

            {/* Address */}
            <div className="border-t border-black/5 pt-6 space-y-4">
              <div className="w-full h-44 bg-[#e5eee0] border border-[#cbe0c2] rounded-2xl relative overflow-hidden flex items-center justify-center">
                <div className="absolute inset-0 bg-[radial-gradient(#a3c993_1px,transparent_1px)] [background-size:16px_16px] opacity-40" />
                <div className="relative z-10 flex flex-col items-center text-center p-4">
                  <span className="material-symbols-outlined text-3xl text-[#FF5A65] animate-bounce">location_on</span>
                  <span className="text-xs font-bold text-[#0E1F38] mt-1">Layo Warehouse Hub</span>
                  <span className="text-[10px] text-[#0E1F38]/60">Gurugram & Mumbai, India | Toronto, Canada</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── FOOTER ── */}
      <footer className="bg-[#ECEAE0] border-t border-black/10 py-12 px-6 md:px-16 text-[#0E1F38]">
        <div className="max-w-5xl mx-auto space-y-8">
          <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6 border-b border-black/10 pb-8">
            <div className="space-y-1">
              <h3 className="text-2xl font-bold tracking-tight text-[#0E1F38]">
                Indian Shipping Made Easy.
              </h3>
              <p className="text-xs text-[#0E1F38]/60">Consolidating purchases, cutting logistics costs, bringing India closer.</p>
            </div>
            <div className="flex flex-wrap gap-4 text-xs font-bold uppercase tracking-wider text-[#0E1F38]/60">
              <Link href="/shipping-policy" className="hover:text-black transition-colors">Shipping Policy</Link>
              <Link href="/privacy" className="hover:text-black transition-colors">Privacy Policy</Link>
              <Link href="/refund-policy" className="hover:text-black transition-colors">Refund Policy</Link>
              <Link href="/terms" className="hover:text-black transition-colors">Terms & Conditions</Link>
              <Link href="/faq" className="hover:text-black transition-colors">FAQs</Link>
            </div>
          </div>
          <div className="flex flex-col sm:flex-row justify-between items-center gap-4 text-xs text-[#0E1F38]/60">
            <p>© 2026 Layo Technologies Inc. All rights reserved.</p>
            <p className="text-[10px] italic">Layo is a parcel forwarding service provider.</p>
          </div>
        </div>
      </footer>

      {/* Estimator Modal */}
      <EstimatorModal isOpen={modalOpen} onClose={() => setModalOpen(false)} />

    </div>
  );
}
